apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nas-a-record
  namespace: network
spec:
  endpoints:
  - dnsName: nas.internal.wat.sn
    recordTTL: 60
    recordType: A
    targets: 
    - 10.0.40.50