apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vrising-data
  namespace: external
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 10Gi