apiVersion: v1
kind: Service
metadata:
  name: vrising
  namespace: external
spec:
  type: LoadBalancer
  selector:
    app: vrising
  ports:
    - port: 27015
      targetPort: 27015
      protocol: UDP
      name: server-port
    - port: 27016
      targetPort: 27016
      protocol: UDP
      name: query-port
