apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-tls
  namespace: teleport
spec:
  secretName: teleport-tls
  dnsNames:
    - teleport.internal.wat.sn
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
