apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: external
spec:
  interval: 5m
  chart:
    spec:
      chart: calibre-web
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
    service:
      main:
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        type: pvc
        mountPath: config
        storageClass: freenas-iscsi-csi
        size: 1Gi
      books:
        enabled: true
        existingClaim: calibre-config
        mountPath: /books
        