---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: https://1pconnect.internal.wat.sn
      vaults:
        k8s-home: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: 1pconnect-credentials
            key: token
            namespace: external-secrets