apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-postgres
  namespace: media
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cluster
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    type: postgresql
    version:
      postgresql: "18"
      mode: standalone

    cluster:
      instances: 2
      imageName: "ghcr.io/tensorchord/cloudnative-vectorchord:18-1.1.1@sha256:392b53675b403d6a2c72b673cc488a7c272514755dd818c622fb9ce4665193c4"
      storage:
        size: 5Gi
        storageClass: freenas-nfs-csi
      enableSuperuserAccess: false
      enablePDB: true

      monitoring:
        enabled: true
        prometheusRule:
          excludeRules:
            - CNPGClusterHAWarning

      postgresql:
        shared_preload_libraries:
          - vchord

      initdb:
        database: immich
        owner: immich
