apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-postgres
  namespace: media
spec:
  chart:
    spec:
      chart: cluster
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  interval: 30m
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: postgresql.cnpg.io
              version: v1
              kind: Cluster
              name: immich-postgres-cluster
            patch: |
              - op: add
                path: /spec/postgresql/extensions
                value:
                  - name: vchord
                    image:
                      reference: ghcr.io/tensorchord/vchord-scratch:pg17-v1.1.1@sha256:72b7cf886db4fafc3cfd831ff418b9effcee9f4a056d196bff219f914723ff23
  values:
    type: postgresql
    version:
      postgresql: "17"
      mode: standalone

    cluster:
      instances: 1
      imageName: "ghcr.io/cloudnative-pg/postgresql:17@sha256:d394417ac1209f7ad074eed7dc7f5078a8fe3de174032ad6c1488e2274df99be"
      storage:
        size: 5Gi
        storageClass: freenas-nfs-csi
      enableSuperuserAccess: false
      enablePDB: true

      initdb:
        database: immich
        owner: immich
