---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: internal
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: nfd-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: v0.17.1@sha256:9371e7fca68d5ed82a36abd9514d88b07e3812e0d2962eb431fba2521ef378f7
    worker:
      config:
        core:
          labelSources:
            - pci
            - usb