---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: internal
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.4
      sourceRef:
        kind: HelmRepository
        name: nfd-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: v0.16.5@sha256:582bc092030a73a24bb0fe6ba331ec18572c5ab4bd2dc1df8b27a49f95f8d305
    worker:
      config:
        core:
          labelSources:
            - pci
            - usb