---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: internal
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.15.4
      sourceRef:
        kind: HelmRepository
        name: nfd-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: v0.15.4@sha256:21c2681deb07aaa1eac74daef2c576392fcc9c72c87ffd4f43769e8a7cd39ddd
    worker:
      config:
        core:
          labelSources:
            - pci
            - usb