---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: internal
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.2
      sourceRef:
        kind: HelmRepository
        name: nfd-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: v0.16.3@sha256:d3950e366f8425de2579b7a2fb2c9d85f3e274fe00570047f64bf542b06dfe26
    worker:
      config:
        core:
          labelSources:
            - pci
            - usb