---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: internal
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: nfd-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: v0.17.2@sha256:b86ad9a33a42dc371fe32a7c67d0705c6246db0a7fa8f0c119810582e6199241
    worker:
      config:
        core:
          labelSources:
            - pci
            - usb