# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wishly
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: artifact-registry-creds      
    controllers:
      main:
        containers:
          api:
            image:
              repository: us-east1-docker.pkg.dev/wishly-401600/docker/wishly
              tag: 0.2@sha256:e56d95a7aa512bfcc5bc08dc9dd6bee99fe8dab6f3ffadd4d7cc9a46965ebad8
            env:
              PORT: &apiPort 8080
              DB_HOST: db.prod.wishly.internal.wat.sn
              DB_PORT: 5432
              DB_NAME: wishly
              DB_USER: wishly
              DB_PASS:
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: password
    service:
      main:
        controller: main
        ports:
          http:
            port: *apiPort
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &ihost "wishly.internal.wat.sn"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
          - host: &host "wishly.wat.sn"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
              - *ihost
            secretName: wishly-cert