---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared-ingress-tunnel
  name: cloudflared-ingress-tunnel
  namespace: network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-ingress-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-ingress-tunnel
    spec:
      containers:
      - image: cloudflare/cloudflared:2024.4.0@sha256:f2a8f348ad721b1a5f2836ca63c08d9a7629081e086a530c8b8bf05bc7fe0f01
        name: cloudflared
        args:
          - "tunnel"
          - "run"
        volumeMounts:
          - mountPath: /etc/cloudflared
            name: cloudflared-tunnel-config
          - mountPath: /etc/cloudflared/creds/
            name: cloudflared-tunnel-creds
      nodeSelector:
        kubernetes.io/arch: "amd64"
      volumes:
        - name: cloudflared-tunnel-config
          configMap:
            name: cloudflared-tunnel-config
        - name: cloudflared-tunnel-creds
          secret:
            secretName: cloudflared-tunnel-file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-tunnel-config
  namespace: network
data:
  config.yaml: |-
    tunnel: 7ee38124-518c-45fd-9a9a-066b8d2bb344
    credentials-file: /etc/cloudflared/creds/creds.json

    ingress:
      - hostname: auth.wat.sn
        service: https://auth.internal.wat.sn:443
      - hostname: photos.wat.sn
        service: https://photos.internal.wat.sn:443
      - hostname: wishly.wat.sn
        service: https://wishly.internal.wat.sn:443
      - service: http_status:404