apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos-postgresql
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cluster
      version:  0.6.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    type: postgresql
    version:
      postgresql: "16"
      mode: standalone

    cluster:
      instances: 2
      imageName: "ghcr.io/cloudnative-pg/postgresql:16@sha256:4418a66c2232ba0bd63dd6c7a98ee401bcac340efbb5f380f8879d004654a7d3"
      storage:
        size: 10Gi
        storageClass: "freenas-nfs-csi"
      services:
        disabledDefaultServices: ["ro", "r"]
      certificates:
        serverCASecret: memos-db-cert
        serverTLSSecret: memos-db-cert
      enableSuperuserAccess: false
      enablePDB: true

      monitoring:
        enabled: true
        prometheusRule:
          excludeRules:
            - CNPGClusterHAWarning

      initdb:
        database: memos
        secret:
          name: memos-db
