apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: external
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 3.1.3
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 5m
  values:
    minecraftServer:
      eula: true
      pvp: true
      type: VANILLA
      whitelist: valtoro 
      ops: valtoro
      bukkitDownloadUrl: https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.16.5.jar
      worldSaveName: test-world
      serviceType: LoadBalancer
      difficulty: hard
      externalTrafficPolicy: Cluster
    persistence:
      storageClass: freenas-iscsi-csi
      dataDir:
        enabled: true
        Size: 1Gi
    serviceAnnotations: 
       external-dns.alpha.kubernetes.io/hostname: minecraft.external.corywatson.net.