apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cnpg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version:  0.26.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  interval: 30m
  values:
    crds:
      create: true
    monitoring:
      podMonitorEnabled: false