apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  interval: 5m
  chart:
    spec:
      chart: openfaas
      sourceRef:
        kind: HelmRepository
        name: openfaas-charts
        namespace: flux-system
      interval: 10m
  values:
    functionNamespace: openfaas-fn
    exposeServices: false
    ingress:
      enabled: true
      hosts:
      - host: functions.internal.corywatson.net
        serviceName: gateway
        servicePort: 8080
        path: /
      annotations:
        external-dns.alpha.kubernetes.io/hostname: functions.internal.corywatson.net.
    generateBasicAuth: true
    operator:
      create: true
     