apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: external-dns
      version: 1.21.1
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 5m
  values:
    provider:
      name: coredns
    domainFilters:
      - internal.corywatson.net
      - external.corywatson.net
      - internal.wat.sn
    sources:
      - service
      - ingress
      - crd
    policy: upsert-only
    interval: 1m
    extraArgs:
      - --crd-source-kind=DNSEndpoint
    env:
      - name: ETCD_URLS
        value: "https://10.0.99.50:2379,https://10.0.99.51:2379,https://10.0.99.52:2379"
      - name: ETCD_CERT_FILE
        value: /etc/coredns/tls/etcd/server-client.crt
      - name: ETCD_KEY_FILE
        value: /etc/coredns/tls/etcd/server-client.key
      - name: ETCD_CA_FILE
        value: /etc/coredns/tls/etcd/server-ca.crt
    extraVolumes:
      - name: etcd-certs
        secret:
          secretName: etcd-certs
          defaultMode: 0400
    extraVolumeMounts:
      - name: etcd-certs
        mountPath: /etc/coredns/tls/etcd
        readOnly: true
