apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 4.9.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    provider: coredns
    coredns:
      etcdEndpoints: "http://etcd-cluster-client:2379"