apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 9.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    domainFilters:
     - internal.corywatson.net
     - external.corywatson.net
     - internal.wat.sn
    provider: coredns
    coredns:
      etcdEndpoints: "https://10.0.99.50:2379,https://10.0.99.51:2379,https://10.0.99.52:2379"
      etcdTLS:
        enabled: true
        secretName: etcd-cert-secrets
        caFilename: server-ca.crt
        certFilename: server-client.crt
        keyFilename: server-client.key
    crd: 
      create: true
      apiVersion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
    sources: 
      - service
      - ingress
      - crd