---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 44
          - 109
          - 65539
    controllers:
      main:
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          external-dns.alpha.kubernetes.io/hostname: media.internal.wat.sn.
        ports:
          http:
            port: 8096
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: watch.internal.wat.sn
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - watch.internal.wat.sn
            secretName: jellfyin-ingress-cert
    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 10.0.40.50
        path: /mnt/root/media
        globalMounts:
          - path: /storage/media
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
