---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: botkube-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://infracloudio.github.io/charts
  timeout: 3m