---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: code-server-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://code-server-boilerplates.github.io/charts
  timeout: 3m