# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://immich-app.github.io/immich-charts
  timeout: 3m