apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - democratic-csi-charts.yaml
  - coredns-chart.yaml
  - sealed-secrets-charts.yaml
  - botkube-charts.yaml
  - bitnami-charts.yaml
  - ingress-nginx-chart.yaml