---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freenas-nfs
  namespace: kube-system
spec:
  releaseName: freenas-nfs
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 5m
  values:
    csiDriver:
    # should be globally unique for a given cluster
    name: "org.democratic-csi.nfs"

    storageClasses:
    - name: freenas-nfs-csi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs

      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 10.0.40.50
          port: 80
          username: root
          password: "************"
          allowInsecure: true
        sshConnection:
          host: 10.0.40.50
          port: 22
          username: k8s
          password: 
            secret: ""
        zfs:
          datasetParentName: hdd/k8s/nfs/vols
          detachedSnapshotsDatasetParentName: hdd/k8s/nfs/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: k8s
          datasetPermissionsGroup: wheel
        nfs:
          shareHost: 10.0.40.50
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: k8s
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""