apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freenas-nfs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: freenas-secrets
      valuesKey: user
      targetPath: driver.config.httpConnection.username
    - kind: Secret
      name: freenas-secrets
      valuesKey: user
      targetPath: driver.config.sshConnection.username
    - kind: Secret
      name: freenas-secrets
      valuesKey: password
      targetPath: driver.config.httpConnection.password
    - kind: Secret
      name: freenas-secrets
      valuesKey: password
      targetPath: driver.config.sshConnection.password
    - kind: Secret
      name: freenas-secrets
      valuesKey: host
      targetPath: driver.config.httpConnection.host
    - kind: Secret
      name: freenas-secrets
      valuesKey: host
      targetPath: driver.config.sshConnection.host
    - kind: Secret
      name: freenas-secrets
      valuesKey: host
      targetPath: driver.config.nfs.shareHost
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"
      version: 1.4.0
      attachRequired: false


    storageClasses:
    - name: freenas-nfs-csi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
      - noatime
      - nfsvers=4.2
    controller:
      externalAttacher:
        enabled: false
    driver:
      config:
        driver: freenas-nfs
        httpConnection:
          protocol: http
          #host: ''
          port: 80
          #username: ''
          # password: ''
          allowInsecure: true
        sshConnection:
          #host: ''
          port: 22
          #username: ''
          #password: ''
        zfs:
          datasetParentName: root/k8s/nfs/vols
          detachedSnapshotsDatasetParentName: root/k8s/nfs/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 1000
          datasetPermissionsGroup: 1000
        nfs:
          # shareHost
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""