apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: external
spec:
  interval: 5m
  chart:
    spec:
      chart: calibre
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
    service:
      main:
        type: LoadBalancer
      webserver:
        enabled: true
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        type: pvc
        mountPath: config
        storageClass: freenas-iscsi-csi
        size: 10Gi