apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: etcd
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 2
    persistence:
      storageClass: freenas-iscsi-csi
      size: 2Gi
    