---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretName
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        oidc_client_id: "{{ .username }}"
        oidc_client_secret: "{{ .password }}"
        oidc_configuration_url: "{{ .url }}"
  dataFrom:
    - extract:
        key: *secretName
