# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: neosmemo/memos
              tag: 0.26.1@sha256:806abfd3743a23dc9f2dfc2b19e5f1464a8e1d79ad4ad8eeb4545cf288bbf137
            env:
              MEMOS_PORT: &apiPort 5230
              MEMOS_DRIVER: postgres
              MEMOS_DSN:
                valueFrom:
                  secretKeyRef:
                    name: memos-db
                    key: memos-dsn

    service:
      main:
        controller: main
        ports:
          http:
            port: *apiPort
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          # proxy-body-size is set to 0 to remove the body limit on file uploads
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &ihost "memos.internal.wat.sn"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
          - host: &host "memos.wat.sn"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
              - *ihost
            secretName: memos-cert
    persistence:
      resources:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: memos-resources
        advancedMounts:
          main:
            main:
              - path: /var/opt/memos
