apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-resources
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
