# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: wishly-staging
spec:
  chart:
    spec:
      chart: postgresql
      version: 15.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  interval: 30m
  values:
    global:
      postgresql:
        auth:
          existingSecret: postgresql-secret
          database: wishly
          username: wishly
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 17.3.0@sha256:51db17ce1aa19e1b4ba65bf4ff45f0afcde6b59e44623d0005142703b91f4a1e
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-data
      service:
        type: LoadBalancer
        # loadBalancerIP:
