apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  releaseName: external
  chart:
    spec:
      chart: cert-manager
      version: v1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
      interval: 5m


kubectl create secret generic cloudflare-secrets -n cert-manager --from-literal=email=corylwtsn@gmail.com \
--from-literal=api_token=nvyLv1tb-RRE4fdZFl-o8sV3I7WpY0k1ds0BinoH \
--dry-run=client -o yaml >