apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certmanager-sealed-secrets.yaml
  - helmrelease.yaml
  - production-issuer.yaml
  - self-signed.yaml
  - staging-issuer.yaml
