apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.4.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: pg_user
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-secrets
      valuesKey: pg_pass
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
  values:
    global:
      image:
        tag: 2024.4.2
    redis:
      enabled: true
    postgresql:
      enabled: true
      auth:
        username: authentik-user
        existingSecret: authentik-secrets
        secretKeys:
          userPasswordKey: pg_pass
      primary:
        persistence:
          enabled: true
          existingClaim: data-authentik-postgresql-0
    geoip:
      enabled: true
      existingSecret:
        secretName: authentik-secrets
        accountId: geoip_id
        licenseKey: geoip_key
    server:
      ingress: 
        enabled: true
        ingressClassName: "nginx"
        tls:
          - hosts:
            - auth.internal.wat.sn
            - auth.wat.sn
            secretName: auth-cert
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts: 
        - auth.internal.wat.sn   
        - auth.wat.sn