apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.12.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-secrets
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: secretKey
      targetPath: authentik.secret_key
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2024.12.2@sha256:017794a605d295bf1029da317e572f379e7f25d9b6fcae2fe7dad0d4b0753b42
    redis:
      enabled: true
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            existingSecret: authentik-secrets
            database: authentik
            username: authentik-user
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 16.4.0@sha256:75c5d322fd11bb10a0e4ddebf4ab312aa9ec2bbcf2b64986f7d87127483e2b14
      primary:
        persistence:
          enabled: true
          existingClaim: authentik-postgres
    geoip:
      enabled: false
      existingSecret:
        secretName: authentik-secrets
        accountId: geoipId
        licenseKey: geoipKey
    server:
      ingress: 
        enabled: true
        ingressClassName: "nginx"
        tls:
          - hosts:
            - auth.internal.wat.sn
            - auth.wat.sn
            secretName: auth-cert
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts: 
        - auth.internal.wat.sn   
        - auth.wat.sn