apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  dependsOn:
    - name: authentik-postgres
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: authentik
      version: 2026.5.6
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-postgres-cluster-app
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-postgres-cluster-app
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: secretKey
      targetPath: authentik.secret_key
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2026.5.6@sha256:ed120caf710ccf82ef0026f0bc74e51615bc95ebff228a7a2d6fc60c441c3868
    authentik:
      postgresql:
        host: authentik-postgres-cluster-rw
        name: authentik
    geoip:
      enabled: false
      existingSecret:
        secretName: authentik-secrets
        accountId: geoipId
        licenseKey: geoipKey
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 30s
      route:
        main:
          enabled: true
          hostnames:
            - auth.internal.wat.sn
            - auth.wat.sn
          parentRefs:
            - name: traefik-gateway
              namespace: network
              sectionName: websecure
    worker:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 30s
