apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-secrets
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: secretKey
      targetPath: authentik.secret_key
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2024.6.2@sha256:a98f95518269d01bb812eb0e12c6647f3d08a36e37b9fdbdccf9345d4431b9f0
    redis:
      enabled: true
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            existingSecret: authentik-secrets
            database: authentik
            username: authentik-user
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 16.3.0@sha256:6b7ea9d12058021fac66d4bf85bcdfd0601dce9abdba8d4187a2d5f485e25df7
      primary:
        persistence:
          enabled: true
          existingClaim: authentik-postgres
    geoip:
      enabled: false
      existingSecret:
        secretName: authentik-secrets
        accountId: geoipId
        licenseKey: geoipKey
    server:
      ingress: 
        enabled: true
        ingressClassName: "nginx"
        tls:
          - hosts:
            - auth.internal.wat.sn
            - auth.wat.sn
            secretName: auth-cert
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts: 
        - auth.internal.wat.sn   
        - auth.wat.sn