apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 3.0.0
      
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: pg_user
      targetPath: postgresql.postgresqlUsername
    - kind: Secret
      name: authentik-secrets
      valuesKey: pg_pass
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: authentik-secrets
      valuesKey: pg_user
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-secrets
      valuesKey: pg_pass
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: geoip_id
      targetPath: geoip.accountId
    - kind: Secret
      name: authentik-secrets
      valuesKey: geoip_key
      targetPath: geoip.licenseKey
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
  values:
    image:
        tag: 2021.9.1
    redis:
      enabled: true
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
        accessModes:
          - ReadWriteOnce
    geoip:
      enabled: true
    ingress: 
      enabled: true
      ingressClassName: "nginx"
      tls:
        - hosts:
          - auth.internal.corywatson.net
          secretName: auth-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts: 
      - host: auth.internal.corywatson.net   
        paths:   
        - path: "/"      
          pathType: Prefix  
      - host: auth.external.corywatson.net   
        paths:   
        - path: "/"      
          pathType: Prefix  
      - host: auth.corywatson.net   
        paths:   
        - path: "/"      
          pathType: Prefix
  