---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: gcr-artifact-registry
spec:
  externalSecretName: artifact-registry-creds2
  namespaceSelector:
      matchLabels: 
        artifact-registry: "true"
  refreshTime: 5m
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    target:
      creationPolicy: Owner
      deletionPolicy: "Delete"
      template:
        type: kubernetes.io/dockerconfigjson
        engineVersion: v2
        data:
          .dockerconfigjson: '{"auths":{"https://us-east1-docker.pkg.dev":{"username":"_json_key","password":"{{ .artifactRegistry }}"}}}'
    dataFrom:
    - extract:
        key: artifactRegistry