apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: code-server
  namespace: external
spec:
  interval: 5m
  chart:
    spec:
      chart: code-server
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: code-server-charts
        namespace: flux-system
      interval: 5m
  values:
    extraArgs:
      - "--auth"
      - "none"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
      tls:
        - hosts:
          - dev.external.corywatson.net
          secretName: code-server-cert
      hosts: 
      - host: dev.external.corywatson.net
        paths:
        - /
      - host: dev.corywatson.net
        paths:
        - /
    persistence:
      storageClass: freenas-iscsi-csi
