apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: etcd
      version: 6.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1h
  values:
    persistence:
      storageClass: freenas-iscsi-csi
    