apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBtSSgNstua0km0steeyVToaI5vF8OiBBvwcfGzUtVpoB3joJkfoz/Dcs+JCb081C3h5o9pWwTQTdCK09OzzRm2fRcGIZFksJWJtHMzmwnfxkX3Vf1IdwHjDig6ryOw/zuMsoAVyK3PEmdZI+zvEvSomMqKoz3lQwVZRXs3NUSAlmux8K+kmVhBAzTUpKR+b9kdthty5yeVq3GYLwNym4vLJUNVGqZvTqJwHiCXtg4L+OxyEC0ACgn8AhlhLFqUUiW7lyDPm/uPZZNOyxRTjvgcNDe8U82AF20Y+lX1JAkCxIJ0pfiXeyinqVnERaidNOQ3rDKanI0/5qQJy3P696iy+wN7JAPYcPfTtzKj4Hqm07Je9p44IVgRqJt6UYIZtJPMspZS8o/jyHUrbrhyFBL2ZWf5VqLAXPFUP6LlZ+meEZ6MKtirvlrNaUDNRUarhJmvJ55wh4EVDORc81Yu5fWk8vDE7AGpIhvk1BsIWqrpeOtDGbSPR6uZWx6G0uCmQWd+dFU40lS+gLL7dJcxZkggknunqJNkxWuk91e04erEGce3UbGN7yDdrdeOulV4Odn40lu/H0HmnXVyQU3A4juaoiiUsEJqIq9i7rOzQyP9GMUyHU1X0OJEoKNBO0MeE2nq//RpJJk6l4CNrWdG/7y7GRp3TRCJChCyuL3HXDCFNhZDUFhkVR/B2vaW7LtOi5EsmIer8ar/NLGhgC+H1O9C9od/ORVLfrZpmbRPkllDtN5GOU5f5p8YdvcqVLpOivIp+wiztrh+I6YfppuZEcTyfoLtvi7vG0w/CCLPUA7E1AvHC23cMOBuxJBSq5EbapiLVewVN/umMR1DEtczRVauCN84JWNt2GucZZc=
  template:
    metadata:
      creationTimestamp: null
      name: discord-url
      namespace: flux-system

