apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.24.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-chart
        namespace: flux-system
      interval: 10m