apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app planka
spec:
  chart:
    spec:
      chart: *app
      version:  1.1.1
      sourceRef:
        kind: HelmRepository
        name: planka-charts
        namespace: flux-system
  interval: 30m
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/plankanban/planka
      pullPolicy: IfNotPresent
      tag: 1.26.3@sha256:e469d724985db3f560ef0aa2218d54536212459bf8ecbdbc9fd995fc3cbe29db

    existingSecretkeySecret: planka

    existingAdminCredsSecret: planka
    
    ingress:
      enabled: true
      className: "nginx"
      annotations:
         cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &appHost planka.wat.sn
          paths:
            - path: /
              pathType: ImplementationSpecific
        - host: &appHostInternal planka.internal.wat.sn
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: planka-cert
        hosts:
        - *appHost
        - *appHostInternal

    postgresql:
      enabled: true
      auth:
        database: planka
        existingSecret: planka-db
      serviceBindings:
        enabled: true
      primary:
        persistence:
          enabled: true
          existingClaim: planka-postgresql

    oidc:
      enabled: true
      existingSecret: "planka"
      issuerUrl: "https://auth.wat.sn/application/o/planka/"
      admin:
        rolesAttribute: groups
        roles:
          - planka-admin