---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app planka
spec:
  driftDetection:
    mode: enabled
  dependsOn:
    - name: planka-postgres
  chart:
    spec:
      chart: *app
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: planka-charts
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/plankanban/planka
      pullPolicy: IfNotPresent
      tag: 2.1.1@sha256:19b507ae3ab5cb1855c3f6984249e4a4881ed0b912febdfd492139c29bf10f39

    existingSecretkeySecret: planka
    existingAdminCredsSecret: planka
    existingDburlSecret: planka-postgres-cluster-app

    persistence:
      enabled: true
      existingClaim: planka-data

    ingress:
      enabled: true
      className: "nginx"
      annotations:
         cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &appHost planka.wat.sn
          paths:
            - path: /
              pathType: ImplementationSpecific
        - host: &appHostInternal planka.internal.wat.sn
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: planka-cert
        hosts:
        - *appHost
        - *appHostInternal

    postgresql:
      enabled: false

    oidc:
      enabled: true
      existingSecret: "planka"
      issuerUrl: "https://auth.wat.sn/application/o/planka/"
      admin:
        rolesAttribute: groups
        roles:
          - planka-admin
