apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-postgresql
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
