---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg
  namespace: media
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16@sha256:096c60451f809596865f37eb99ee99d23b20b0d54fb889bb35119fc2283f2f76

  postgresql:
    shared_preload_libraries:
      - vchord.so
    extensions:
      - image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg16-v1.1.1@sha256:b15cd02051cad0a8f4cb02dbd4cbdfee0acedbcd4c986337d0a1ddd1006a0feb

  storage:
    size: 5Gi
    storageClass: freenas-nfs-csi

  enableSuperuserAccess: false
  enablePDB: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
