---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg
  namespace: media
spec:
  instances: 1
  imageName: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.3.0@sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891

  postgresql:
    shared_preload_libraries:
      - vectors.so
      - vchord.so

  storage:
    size: 5Gi
    storageClass: freenas-nfs-csi

  enableSuperuserAccess: false
  enablePDB: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      import:
        type: microservice
        databases:
          - immich
        source:
          externalCluster: existing-postgres

  externalClusters:
    - name: existing-postgres
      connectionParameters:
        host: immich-postgresql.media.svc.cluster.local
        user: postgres
        dbname: immich
        sslmode: disable
      password:
        name: immich-postgresql
        key: postgres-password
