---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg
  namespace: media
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14-debian@sha256:0009d5149042bf8295e3853be88dccb39bb6668901a092e80ddb45c43f70e204

  postgresql:
    shared_preload_libraries:
      - vchord.so
    extensions:
      - image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg14-v1.1.1@sha256:9c0e2aca1ff1888abd9632f42dc8d3a0be648c755c182496908a3d802056c55a

  storage:
    size: 5Gi
    storageClass: freenas-nfs-csi

  enableSuperuserAccess: false
  enablePDB: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
