---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: media
spec:
  driftDetection:
    mode: enabled
  dependsOn:
    - name: immich-postgres
  chart:
    spec:
      chart: immich
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    controllers:
      main:
        containers:
          main:
            env:
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              DB_HOSTNAME: "immich-postgres-cluster-rw"
              DB_USERNAME: "immich"
              DB_DATABASE_NAME: "immich"
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-cluster-app
                    key: password
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-storage

    valkey:
      enabled: true

    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                pullPolicy: IfNotPresent
                tag: v3.3.1@sha256:db996e352359771c6a3db121a0ed8761516b22f727fc092a0f46dcfef82c1bc1
      route:
        main:
          kind: HTTPRoute
          hostnames:
            - photos.internal.wat.sn
            - photos.wat.sn
          parentRefs:
            - name: traefik-gateway
              namespace: network
              sectionName: websecure

    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                pullPolicy: IfNotPresent
                tag: v3.3.1-openvino@sha256:9f5ea923b763435592280e2f5e051a62f1a33d6d14e87620fc15453c27a12ae0
              resources:
                requests:
                  gpu.intel.com/i915: "1"
                limits:
                  gpu.intel.com/i915: "1"
              env:
                TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          storageClass: freenas-iscsi-csi
