---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: media
spec:
  driftDetection:
    mode: enabled
  dependsOn:
    - name: immich-postgres
  chart:
    spec:
      chart: immich
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    controllers:
      main:
        containers:
          main:
            env:
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              DB_HOSTNAME: "immich-postgres-cluster-rw"
              DB_USERNAME: "immich"
              DB_DATABASE_NAME: "immich"
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-cluster-app
                    key: password
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-storage

    valkey:
      enabled: true

    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                pullPolicy: IfNotPresent
                tag: v3.2.0@sha256:ae13784ffcfcce8f4178113eb6661602a1fd1912f3d539880b8ac0dd95fc8ac2
      route:
        main:
          kind: HTTPRoute
          hostnames:
            - photos.internal.wat.sn
            - photos.wat.sn
          parentRefs:
            - name: traefik-gateway
              namespace: network
              sectionName: websecure

    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                pullPolicy: IfNotPresent
                tag: v3.2.0-openvino@sha256:6387b84ab42da139191c3db686faead6555ab8cac6466d1d20be955735961b98
              resources:
                requests:
                  gpu.intel.com/i915: "1"
                limits:
                  gpu.intel.com/i915: "1"
              env:
                TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          storageClass: freenas-iscsi-csi
