apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-storage
  namespace: media
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
