apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-storage
  namespace: media
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db
  namespace: media
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis
  namespace: media
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
