---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 30m
  maxHistory: 3
  # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.0.1/charts/other/app-template/values.schema.json
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.7.1@sha256:5ed76e1de666b3522dcbef5d23e41283c925dd707dbcaa2fc0ecef981c0bc881
            env:
              TZ: "America/New_York"
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.100.3@sha256:c5b7ec231b24f26ecee243e8d9f9df57af906d03c9c8238efd893217c9f1f725
            args:
              - --auth=none
              - --user-data-dir=/config/.vscode
              - --extensions-dir=/config/.vscode
              - --port=8080
              - /config
              - --disable-update-check
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: app
        ports:
          http:
            port: 8123
          code-server:
            port: 8080

    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &ihost "ha.internal.wat.sn"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: &host "ha.wat.sn"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
              - *ihost
            secretName: home-assistant-cert
      code:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &codeihost "ha-code.internal.wat.sn"
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server
        tls:
          - hosts:
              - *codeihost
            secretName: home-assistant-code-cert
    persistence:
      config:
        existingClaim: home-assistant-config
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
