---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/values.schema.json
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.6.2@sha256:124cfd97bf15112d770cd60d1ded0eb8739fb3123b9a32bf85978d4cfa27b1a3
            env:
              TZ: "America/New_York"
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.123.0@sha256:6d46b83ea0687ab1826ec029b6d0e6342bbd55cc5c29b98258463e7faee16d1e
            args:
              - --auth=none
              - --user-data-dir=/config/.vscode
              - --extensions-dir=/config/.vscode
              - --port=8080
              - /config
              - --disable-update-check
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: app
        ports:
          http:
            port: 8123
          code-server:
            port: 8080

    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &ihost "ha.internal.wat.sn"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: &host "ha.wat.sn"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
              - *ihost
            secretName: home-assistant-cert
      code:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &codeihost "ha-code.internal.wat.sn"
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server
        tls:
          - hosts:
              - *codeihost
            secretName: home-assistant-code-cert
    persistence:
      config:
        existingClaim: home-assistant-config
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
