apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: executor-data
  namespace: agents
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 2Gi
