name: Renovate

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.15
        with:
          token: ${{ github.token }}
        env:
          RENOVATE_REPOSITORIES: corylwtsn/k8s-gitops
